version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    networks:
      - bitcoinnanoninja-network
    environment:
      NODE_ENV: 'production'
      DOMAIN: 'http://localhost:3000'
      NODE_RPC: 'https://api.bitcoinnano.org'
      NODE_WS: 'wss://ws.bitcoinnano.org'
      NODE_INTERNAL: '12000'
      MONGO_URL: 'mongodb://db:27017/bitcoinnanoninja'
      MONGO_SESSIONURL: 'mongodb://db:27017/bitcoinnanoninja-session'
      SESSION_SECRET: 'ohyeahnanoisgreat'
      SENTRY_URL: ''
      FACEBOOK_CLIENTID: ''
      FACEBOOK_CLIENTSECRET: ''
      TWITTER_CONSUMERKEY: ''
      TWITTER_CONSUMERSECRET: ''
      GOOGLE_CLIENTID: ''
      GOOGLE_CLIENTSECRET: ''
      GITHUB_CLIENTID: ''
      GITHUB_CLIENTSECRET: ''
      REDDIT_CLIENTID: ''
      REDDIT_CLIENTSECRET: ''
      DISCORD_CLIENTID: ''
      DISCORD_CLIENTSECRET: ''
      EMAIL_HOST: 'smtp.myhost.com'
      EMAIL_USER: 'alert@mynano.ninja'
      EMAIL_PASS: 'mypassword'
      DPOW_USER: 'user'
      DPOW_KEY: 'longhash'
      DRPC_REPSONLINE: '[]'
      VERIFICATION_AMOUNT: '1'
      MATOMO_URL: "https://piwik.org/piwik.php"
      MATOMO_TOKEN: "yourtoken"
      MATOMO_SITE: "1"
      PORT: 3000
  db:
    image: mongo
    networks:
      - bitcoinnanoninja-network
    ports:
      - "27017:27017"

networks:
  bitcoinnanoninja-network:
    driver: bridge
